name: Deploy to AWS S3
on: push
jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Build
        env:
          ABOUT_ME: ${{ vars.ABOUT_ME }}
          AUTHOR: ${{ vars.AUTHOR }}
          DESCRIPTION: ${{ vars.DESCRIPTION }}
          EARNED_CERTS: ${{ vars.EARNED_CERTS }}
          ENDPOINT: ${{ vars.ENDPOINT }}
          NAME: ${{ vars.NAME }}
          REPOS: ${{ vars.REPOS }}
          SITEKEY: ${{ vars.SITEKEY }}
          SKILLS: ${{ vars.SKILLS }}
        run: npm run build
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: us-east-1
      - name: Upload changes to S3 and issue Cloudfront invalidations
        uses: vladcosorg/action-s3-cloudfront-smart-deploy@v1
        with:
          source: ./dist
          target: ${{ secrets.AWS_BUCKET }}
          distribution: ${{ secrets.AWS_DISTRIBUTION_ID }}
          invalidation-strategy: 'precise'